import { Knex } from "knex";

const TABLE_NAME = "user_details";

/**
 * Delete existing entries and seed values for table TABLE_NAME.
 *
 * @param   {Knex} knex
 * @returns {Promise}
 */
export function seed(knex: Knex): Promise<void> {
  return knex(TABLE_NAME)
    .del()
    .then(() => {
      return knex(TABLE_NAME).insert([
        {
          uid: 1,
          dob: "1992-09-01",
          bio: "PyT9opcGnxM82zdtQ2zea2H6TioGdT1H9k82rexdEa1Kfi5yP8",
          location: 2,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "xAlWCKfqzT",
        },
        {
          uid: 2,
          dob: "1993-10-21",
          bio: "5q2Oz3682JQqOddfYRcPUNWx8xgIyjNTM41HsLOEWaAdqO5YPe",
          location: 3,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "0eKZLuOHgG",
        },
        {
          uid: 3,
          dob: "1993-03-05",
          bio: "AydmxHGla5kA6vPenVVwnszmO1AhY8Em6x44WyVRnss8MXM9WZ",
          location: 4,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "SoT44OIqKl",
        },
        {
          uid: 4,
          dob: "1996-08-25",
          bio: "Xzoji58ukCEIlNL1cflcOtvLYEjcme5I9VkudHNqHy8Ds1nFxX",
          location: 5,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "CtLjS6FDrH",
        },
        {
          uid: 5,
          dob: "1994-05-05",
          bio: "WILHhxoejtdJHEnZxe785yXs4n6vQy6aDCantzOQ4BMZheHWb7",
          location: 6,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "XdT8Id9z6e",
        },
        {
          uid: 6,
          dob: "1994-12-15",
          bio: "JtMqLLTPXJlnt9unQRXJDBJ67H5x1oaipW1Dh8TeILC41u9nTa",
          location: 7,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "YUNSJlHAzy",
        },
        {
          uid: 7,
          dob: "1995-07-11",
          bio: "55q6JXYlzBtoRD2hTH0Awq8eT0b0UsUrjnfD0IFzoG8GnqpPwb",
          location: 8,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "Cmu8KAXgx2",
        },
        {
          uid: 8,
          dob: "1996-01-02",
          bio: "IMURbal0Ss3KGZ1euuAtiq5pciu8rSFmzf3ZzRCEWZwyFBxeFo",
          location: 9,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "miJweKsj4a",
        },
        {
          uid: 9,
          dob: "1997-12-10",
          bio: "I8wHPdZ5OhHireYo2xHpbcGAwlSODK1XWQP6fuOia5GM9am9g5",
          location: 10,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "d6TOosChOf",
        },
        {
          uid: 10,
          dob: "1996-12-02",
          bio: "SYV2kMLU50Ktn2TwqhTFSVurF1JIhsVldXLIUJgEtoV28CdMw0",
          location: 11,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "kb9bdgSBA3",
        },
        {
          uid: 11,
          dob: "1991-12-04",
          bio: "naqTTaJPTKZzZB0hbww6BGxKZIXB9EIxJLi7TipvKrXZ7xq3RK",
          location: 12,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "6y6UeRcwBq",
        },
        {
          uid: 12,
          dob: "1994-02-13",
          bio: "qS9GQzh30bsGiP5vc69P9Z132IfqOPfQHCXPn90HiowvzNGtt6",
          location: 13,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "LVEACyDG4o",
        },
        {
          uid: 13,
          dob: "1991-06-08",
          bio: "KVC3oDHWwxufOvfFQTcmbJgoMG9ivIrqrav0AIHnkyJgRM1Vbp",
          location: 14,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "EWc5hY1P2F",
        },
        {
          uid: 14,
          dob: "1992-07-05",
          bio: "EpnEGJ9WJY5DuIsIi0RAxWXmS3NDlVdRltCTHC9HevsEZio3Zr",
          location: 15,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "3QQQ0K64Xw",
        },
        {
          uid: 15,
          dob: "1994-09-05",
          bio: "OeTeZFYpOii9WNdQHskplL14a6iqgswt2Mfe52K2MNy0dRxYfZ",
          location: 16,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "foLIwcsCAw",
        },
        {
          uid: 16,
          dob: "1994-03-20",
          bio: "1lA9fHOLQ55wTUPKzNJbc31qpM8zVr1H2JkS4mbbMMso4m7lop",
          location: 17,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "txebcikQKC",
        },
        {
          uid: 17,
          dob: "1991-12-10",
          bio: "W8dgTlhfCaixvS1HblCYgXmtjTHdGoXYjuppobMOZoW0ADP04l",
          location: 18,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "zFKaTPSI7w",
        },
        {
          uid: 18,
          dob: "1998-07-25",
          bio: "y6VcQWyUN3SO5OPe17GQ5zSVAiFYwoZYgYeauzmpBEKWFKQSRT",
          location: 19,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "zTte3xcsW3",
        },
        {
          uid: 19,
          dob: "1994-11-24",
          bio: "TNhpurzxI2s51Ucyv6ihFItbZSPgN9ZEiWPyNt18gusH1Ef4o1",
          location: 20,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "gFnqAlB3G7",
        },
        {
          uid: 20,
          dob: "1998-09-05",
          bio: "7V5lc4H8Bro0WpjN9ylgmzX6LnVNDT7vhejM8BCndp4CE04nd2",
          location: 21,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "GqYr3p20Vh",
        },
        {
          uid: 21,
          dob: "1996-08-20",
          bio: "htRkzm7DkfQ2in0V6UbIRH8rtjFl9sSCYlLSS1LzAXQSF9KjMC",
          location: 22,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "npl5UQSkgp",
        },
        {
          uid: 22,
          dob: "1991-09-20",
          bio: "Gt2jGXVWmsp6FySCNVSReJzfx14gqbYZThu9Zt0nwAGGp7Mqzd",
          location: 23,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "vnskNGzFAT",
        },
        {
          uid: 23,
          dob: "1995-11-04",
          bio: "RrRfsdJIyJWVeY2GrfSvKqpjRRByCYMSH0KHRGuLj9ptCF5Kp9",
          location: 24,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "CcqDGvWIZj",
        },
        {
          uid: 24,
          dob: "1995-05-05",
          bio: "59GuzN2ucsOvqGy27Ch0EwEjp0CCk6NrMpei3VfcpsgYKThqaK",
          location: 25,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "asA2fQEeow",
        },
        {
          uid: 25,
          dob: "1991-02-28",
          bio: "ZvqEGPCgDINxAyBlEdFjPFx7lrMnhg18b5oPqX3PJd1O2uEssa",
          location: 26,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "be0q9cIjoj",
        },
        {
          uid: 26,
          dob: "1994-06-06",
          bio: "P0cIedIUhef8YGxfga92eCaLyJAiz48gK18nwE7ld5lgMnRU16",
          location: 27,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "V29mLTSepr",
        },
        {
          uid: 27,
          dob: "1991-05-05",
          bio: "kO4GENTNd4TJosy5u1jLgSwEiARfJJfoDrGw5Dk9SJ7tc290lA",
          location: 28,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "1vOXm0HLJd",
        },
        {
          uid: 28,
          dob: "1994-08-25",
          bio: "h1CUYBSRed6O126TeZZhcNO5R3fGy15VE6gGkXKvtdeQiaiwZ7",
          location: 29,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "WfaSpU5uIt",
        },
        {
          uid: 29,
          dob: "1997-11-14",
          bio: "OuCePe2vXToDnHVp4HjCJwqZIMdxFTBLEMCCzyPqMywNHQ7SjO",
          location: 30,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "D8pHN1ue74",
        },
        {
          uid: 30,
          dob: "1992-02-28",
          bio: "MBcnCdT7HepSO7uJKJvzP4gtpf7qasprPISe3TahDNnXAEVLxr",
          location: 31,
          gender: 1,
          prefered_gender: 1,
          prefered_age: 25,
          college: "YoIpztn6nl",
        },
      ]);
    });
}
